### ISSUE TITLE
FIX - Configurar labels de issues nos repositórios

### ISSUE THREAD

**Issue by guilherme1guy** [ads-unigrade-2019-1/Wiki#3]
Descrição: 
Criar as labels descritas no GCS em todos os repositórios da organização (com exceção do protótipo) e apagar as que não serão utilizadas. Também é algo legal pensar em mais alguma labels interessante, e caso exista, cria-lá e atualizar o GCS.

Critérios de aceitação:
- [x] Sejam todas as labels do GCS criadas em todos os repositórios da organização
- [x] Sejam todas as labels extras apagadas em todos os repositórios da organização
- [x] Caso haja a criação de novas labels, atualizar GCS com elas
- [x] Atualizar issues já existentes com as novas labels

Prazo:
12/04/2019

**Comment by Guilherme-Aguiar** [comment]
Não tenho permissões para editar as labels do repositório do protótipo, e acho que não seja necessário de qualquer forma.
![image](https://user-images.githubusercontent.com/23269406/56053707-2e1adc80-5d2b-11e9-8ed3-6a659e337685.png)

**Comment by guilherme1guy** [comment]
Tá tudo ok, no protótipo realmente não há a necessidade. A issue está completa.
